### ISSUE TITLE
Mock isn't compatible with latest versions

### ISSUE THREAD

**Issue by abtris** [nagyesta/lowkey-vault-example-go#100]
- github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.11.0 - works
- github.com/Azure/azure-sdk-for-go/sdk/keyvault/azsecrets v0.12.0 - getting 400 bad request for just getting secrets
- The same problem with with actual versions 1.0.1 https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/security/keyvault/azsecrets/CHANGELOG.md

**Comment by nagyesta** [comment]
Hi @abtris ,
thank you for giving Lowkey Vault a chance! As I remember, it is because the new clients are using the v7.4 service version instead of the v7.2 or v7.3 APIs which are implemented in Lowkey Vault.

I have created a new issue to cover the update: https://github.com/nagyesta/lowkey-vault/issues/697
Please feel free to track the progress there. In the meantime, if you know how the service version can be set to v7.3 using the new client, then that could be a potential work-around. I couldn't figure it out easily when I saw the updates originally, and gave up temporarily. If you can reach a working solution, could you please consider sharing it somehow with the community as well?

Thank you in advance!

**Comment by nagyesta** [comment]
Hi @abtris ,
I have updated the Lowkey Vault app to support v7.4 API requests (although only by doing exactly the same as in case of v7.3 for now). Also, updated the dependencies of this example repository.

Please check it out and let me know whether or not it solves your issue!

Thank you!

**Comment by nagyesta** [comment]
Hi,
I assume this is resolved, so I am closing the issue. Please feel free to reopen or create a new issue in case it is not.
Thank you!
